version: '3.1'

services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: cont_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adopet
    volumes:
      - data_mysql:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  data_mysql: